apiVersion: v1
kind: Pod
metadata:
  name: astomind-postgres
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: astro
        - name: POSTGRES_PASSWORD
          value: Strong@Pwd
        - name: POSTGRES_DB
          value: astromind
